### ISSUE TITLE
Live website, what domain?

### ISSUE THREAD

**Issue by sabgaby** [DIYbiosphere/diybiosphere.io#29]
Hey @cube5 none of the names worked for me.
sphere.diybio.org -> just redirected me to diybio.org
diybiosphere.github.io -> 404 page
diybiosphere.io -> blank page

**Comment by jasonbobe** [comment]
yeah, hmmm...it worked for a few days and now broke.

@cube5 let me know if you'd like to check out the DIYbio.org DNS to make sure the CNAME records are correct

**Comment by cube5** [comment]
@jasonbobe Sure no problem, I can take a look.

**Comment by jasonbobe** [comment]
just sent you a message via Gitter

**Comment by sabgaby** [comment]
The domain is working now!
