### ISSUE TITLE
Adjust design according to artboards

### ISSUE THREAD

**Issue by cube5** [DIYbiosphere/diybiosphere.io#4]
@cube5 commented on [Wed Mar 30 2016](https://github.com/DIYbiosphere/diybiosphere.github.io.old/issues/3)

The current design will be readjusted to match the current (and cooler 🤘) artboards.

---

@sabgaby commented on [Wed Mar 30 2016](https://github.com/DIYbiosphere/diybiosphere.github.io.old/issues/3#issuecomment-203453345)

We are in the process of hiring a professional designer! So this should wait a bit!!!

---

@cube5 commented on [Wed Mar 30 2016](https://github.com/DIYbiosphere/diybiosphere.github.io.old/issues/3#issuecomment-203455314)

Nice! no problem I'll drag it in To Do's pipeline

**Comment by cube5** [comment]
### Developed and waiting to be pushed (with functionality):
- [x] Landing
- [x] List of initiatives
- [x] Generic
- [ ] Getting Started

**Comment by sabgaby** [comment]
This issue reflect the old artboards, and the new artboards (v2) opened a new issue as #24 
I am closing this issue as it represents (technically) a duplicate
